### ISSUE TITLE
Permission to push to this repo

### ISSUE THREAD

**Issue by jdlubrano** [MeteorPackaging/nvd3-wrapper#1]
Hey @splendido,

Would you mind providing me with access to push to this repo?

If you would prefer a fork-and-pull workflow, could you initialize this repo with a README (or some arbitrary file)?  Github tells me that I cannot fork an empty repository...

Thanks!

**Comment by jdlubrano** [comment]
@splendido, I don't know if you're aware, but Github is still showing that I have read-only access for this repo.  I saw that you added me to the MeteorPackaging organization and the nvd3 team, which is terrific; thanks for that.

Nevertheless, in case you were not aware, and I do not mean to rush you nor cause a fuss, but it still looks like I cannot push to this repo from my end.

Thanks again.

![image](https://cloud.githubusercontent.com/assets/4729920/10293965/6f60d3a2-6b85-11e5-9b98-1d18a6c6d113.png)

**Comment by splendido** [comment]
Hi @jdlubrano,
I'm sorry I had no time to react any earlier!

I've just turn the permissions to 'Write', let me know if you know have access to it.

**Comment by jdlubrano** [comment]
@splendido simply fantastic!  Looks like I have write access now.  I have a very rough master branch at the moment.  The `try_spacejam` branch is closer to complete...more on that below.

I had two more topics for discussion, one important, one not so important, if you would be willing to share more of your much needed and appreciated advice.
- The autopublish [wiki](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Wrapping-3rd-Party-Packages#version-bump) alludes to tasks like `gulp getUpstream --tag newtag`.  My question is, what drives the _newtag_ parameter?  Does that come from the Github webhook or is it the package's responsibility for figuring that out?  Specifically if the folks at NVD3 use version numbers of the form `v1.8.1`, am I correct in guessing that the gulpfile in this package must gracefully handle the _v_ in the semantic version?  I think that by studying the jspdf-core-wrapper more closely, I understand what's going on.  Still if you wouldn't mind clarifying, it would put my mind at ease.
- Less importantly, have you ever used [Spacejam](https://www.npmjs.com/package/spacejam) to run `tinytest` on your packages?  It seems a little slow, but I like the simplicity of installing one nodejs package versus downloading and installing the aronuda Meteor scripts.  Do you see an obvious problem with using _Spacejam_?

**Comment by splendido** [comment]
yes, the idea is to have an automated script which gets the lates release available for a certain upstream repo and runs, e.g., `gulp getUpstream --tag v1.2.3`. The same applies to `gulp updateVersion` and `gulp updateRelease`.
For now we have to run these tasks manually...

I've never tried Spacejam but it could make sense to give it a try actually ;-)

**Comment by jdlubrano** [comment]
I'm no longer doing Meteor things, so I will go ahead and close this.
